// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUl-hJUpOp9wCCJsfKPdlxQXmpxRHL59M',
    appId: '1:1086146711395:web:e8299a6991b05bae410d56',
    messagingSenderId: '1086146711395',
    projectId: 'openlibrary-book-explorer',
    authDomain: 'openlibrary-book-explorer.firebaseapp.com',
    storageBucket: 'openlibrary-book-explorer.firebasestorage.app',
    measurementId: 'G-MMSFN95BCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgIpLaeeYzGMkyMCFGXb42aCiNL_6szDs',
    appId: '1:1086146711395:android:de506a70a68e6365410d56',
    messagingSenderId: '1086146711395',
    projectId: 'openlibrary-book-explorer',
    storageBucket: 'openlibrary-book-explorer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIcotk7kI9LgKPDWpnLGa1f9lKs2pqq7c',
    appId: '1:1086146711395:ios:103c42831bda864e410d56',
    messagingSenderId: '1086146711395',
    projectId: 'openlibrary-book-explorer',
    storageBucket: 'openlibrary-book-explorer.firebasestorage.app',
    iosBundleId: 'com.example.openlibraryBookExplorer',
  );
}
